joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0

left_front_controller:
  type: velocity_controllers/JointVelocityController
  joint: body_to_left_front
  pid: {p: 100.0, i: 0.01, d: 10.0}
right_front_controller:
  type: velocity_controllers/JointVelocityController
  joint: body_to_right_front
  pid: {p: 100.0, i: 0.01, d: 10.0}
left_rear_controller:
  type: velocity_controllers/JointVelocityController
  joint: body_to_left_rear
  pid: {p: 100.0, i: 0.01, d: 10.0}
right_rear_controller:
  type: velocity_controllers/JointVelocityController
  joint: body_to_right_rear
  pid: {p: 100.0, i: 0.01, d: 10.0}


