car_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : ['body_to_left_front', 'body_to_left_rear']
    right_wheel : ['body_to_right_front', 'body_to_right_rear']
    publish_rate: 50.0               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 1000.0]


    # empirical in real robot
    wheel_separation : 0.3        #0.95 -0.10 rad / rev
    wheel_radius : 0.1    # this is empirical value, but is not corresponding with the physical value

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.2

    # Base frame_id
    base_frame_id: base_link


    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 3.0 # m/s
        min_velocity           : -3.0 # m/s
        has_acceleration_limits: true
        max_acceleration       : 5.00  # m/s^2
        min_acceleration       : -5.00 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 6.0  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 6.0  # rad/s^2

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0
