joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0

laser_controller:
  type: effort_controllers/JointPositionController
  joint: body_to_laser
  pid: {p: 100.0, i: 0.01, d: 10.0}